### ISSUE TITLE
Regarding Angus Script Results

### ISSUE THREAD

**Issue by jueurousseau** [nus-mornin-lab/echo-mimiciii#2]
We used the angus.sql script (https://github.com/MIT-LCP/mimic-code/blob/master/concepts/sepsis/angus.sql) and produced the following.

1) select count(distinct subject_id) from mimiciii_angus_sepsis where angus = 1; -- 12,636 DISTINCT PATIENTS
2) select count(*) from mimiciii_angus_sepsis where angus = 1; -- 15,254 ROW COUNT

This is inconsistent with your results in your paper (https://link.springer.com/article/10.1007%2Fs00134-018-5208-7).
I also found that terms admissions and patients were used interchangeably, but I believe these are distinct variables in MIMIC. Do you mean admissions or patients for your query (i.e. Figure 1)?

**Comment by kiendang** [comment]
We mean icu admission actually.

Using `subject_id` (patient)
```
select count(distinct subject_id) from angus_sepsis where angus = 1;
# 12636
```
Using `hadm_id` (hospital admission)
```
select count(distinct hadm_id) from angus_sepsis where angus = 1;
# 15254
```
Using `icustay_id` (ICU admission, this is what we used in our paper)
```
select count(distinct icustay_id) from icustays a left join angus_sepsis b on a.hadm_id = b.hadm_id where angus = 1;
# 17420
```
