### ISSUE TITLE
About angus_sepsis table

### ISSUE THREAD

**Issue by Yuz998** [nus-mornin-lab/echo-mimiciii#4]
Hello,

I want to know where the angus_sepsis table in the SQL statement comes from? There is no angus_sepsis table in the mimic database. Can you provide the patient table? Or how to generate angus_sepsis table?

![table](https://user-images.githubusercontent.com/46648283/92216338-bf629400-eec8-11ea-8e39-c26e399c6b77.png)

Thanks！

**Comment by tompollard** [comment]
@Yuz998 my guess is that this is referring to the view generated by the script at: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/sepsis/angus.sql. I wrote this script based on the paper at: https://github.com/MIT-LCP/mimic-code/blob/master/concepts/sepsis/angus2001.pdf

**Comment by kiendang** [comment]
Thanks Tom that is correct. We did use several tables from https://github.com/MIT-LCP/mimic-code/blob/master/concepts.
