### ISSUE TITLE
the day of the week

### ISSUE THREAD

**Issue by yinet** [nus-mornin-lab/echo-mimiciii#5]
Your article is very fascinating.
In Table 1 of the article, it is about the day of the week the patient is admitted to the ICU. I would like to know if it is the same the day of the week from the database and the patient is admitted to the ICU in reality?
Thank you!

![Snipaste_2021-01-24_21-12-52](https://user-images.githubusercontent.com/3617360/105631469-8af87000-5e89-11eb-9364-c1020f366952.jpg)

**Comment by kiendang** [comment]
Yes the day of the week is preserved in the database, which means if a timestamp is a Sunday in the database, it was a Sunday in reality. It says here https://mimic.physionet.org/mimicdata/time/

> Day of the week - a measurement made on a Sunday will appear on a Sunday in the future.
