### ISSUE TITLE
About replicating the psm result

### ISSUE THREAD

**Issue by hlblade** [nus-mornin-lab/echo-mimiciii#6]
Hi,
Thanks for your great work and generosity of sharing all of the code, I studied a lot from your code.

I was tring to replicate the psm procedure, but it failed. I have noticed about the update of the twang package and added the version="legacy", but it's still the same.

Could you please sharing your enviroment when you create this project, I mean the version of R and the packages you used. Or I will appreciate it very much if you could provide the data file of the ps result.

Thanks again for you wonderful work.

Best wishes,
Blade

**Comment by kiendang** [comment]
Hi sorry I didn't write down the exact version of those R packages (I should have). I installed them somewhere between Dec 2017 to April 2018. You should be able to use the R `checkpoint` package to install the versions of those packages during that period, just choose a date.

https://mran.microsoft.com/documents/rro/reproducibility#checkpointpkg

**Comment by hlblade** [comment]
Thanks very much for your reply. 
By the way， I have runned your code for many time. the ps matched cohort I generated now also support the main endpoint, the 28 day mortality is lower in the TTE group, but other part like the vaso and MV using in first 24h have no statistically difference between groups im matched cohort any more. How should I understand this result?
Thanks in advanced.

**Comment by kiendang** [comment]
Given that in our original run of the analysis, based on p-value, differences in use of MV and vaso are only marginally significant (p-value 0.025 and 0.02 respectively), it's not unexpected that they are not significant anymore in another run. In the paper we only reported the SMD also because of that reason. We felt that statistical significance based on an arbitrary p-value threshold is not satisfying.

**Comment by hlblade** [comment]
Ok, thanks for your reply, I understand the result may shift from time to time. I can not get the same result when I run the code in my current enviroment for the second time. For understand your work more precisely, could you please share your data files you generated in your original run? I know it's a abrupt request, please ignore it if you think it's time consuming to find them out. Thanks again for the sharing of your work.

**Comment by kiendang** [comment]
I no longer have the original generated files.
